/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_accept[218] =
    {   0,
        0,    0,   38,   36,   35,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   25,   21,    2,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,    4,   34,   34,   34,   34,
       34,   34,   34,    1,   34,   34,   34,   34,   34,   34,

       34,   34,   34,    8,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    7,    0,
       34,   34,   18,   12,    9,   34,   34,   26,   34,   34,
       34,   28,   34,   34,   34,    3,   34,   34,   34,   34,
       20,   34,   27,   15,    0,   34,   34,   34,   34,   34,
       34,   32,   11,   34,   34,   34,   34,   34,    0,   34,
       30,    0,   34,   34,   24,   34,   13,   19,   34,    5,
        0,   34,   34,   34,    0,   34,    0,    6,   23,    0,
       34,   34,    0,   34,   34,   17,    0,   31,    0,    0,
       34,   10,    0,   34,   22,    0,    0,    0,   34,   16,

       16,    0,    0,    0,    0,   34,    0,    0,    0,   34,
        0,   14,   29,   29,    0,   33,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    8,    9,   10,
       11,    8,    8,   12,    8,   13,   14,    8,   15,   16,
        8,    8,   17,   18,    8,   19,    8,    8,    8,    8,
        1,    1,    1,    1,    1,    1,   20,   21,   22,   23,

       24,   10,   25,   26,   27,   28,    8,   29,   30,   31,
       32,   33,    8,   34,   35,   36,   37,   38,    8,    8,
       39,   40,    1,    1,    1,    1,    1,    1,    8,    1,
        1,    1,    1,    1,    1,    1,    8,    1,    1,    1,
        8,    1,    1,    1,    8,    1,    8,    1,    1,    1,
        1,    1,    1,    8,    1,    1,    1,    1,    1,    1,
        8,    1,    1,    1,    1,    1,    1,    1,   41,    1,
        1,    1,    8,    1,    1,    1,   42,    1,    8,    1,
        1,    1,    1,    1,    1,    8,    1,   43,    1,    1,
        1,    1,    1,    1,   44,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    2
    } ;

static yyconst short int yy_base[219] =
    {   0,
        0,    0,  252,  253,  253,  221,   25,   26,    0,   25,
      223,  212,  224,  215,   33,  216,   34,  218,  210,  211,
        0,  222,  219,  206,  217,  208,   31,  211,  203,  206,
      214,  197,  203,   28,  209,  202,  195,  204,   44,   32,
      193,  199,   39,  205,  195,   27,  203,  188,  195,  196,
      185,  196,  195,  196,  188,  182,   42,  181,  185,  187,
      190,  189,  188,    0,    0,  253,  185,  166,  172,  170,
      173,  164,  181,   49,   36,  180,  168,  178,  170,  167,
      161,  168,  167,  169,  160,    0,  158,  169,  152,  167,
      151,  183,  148,    0,  157,  162,  149,  160,  152,  154,

      142,  156,  148,    0,  151,  141,  150,  138,  141,  149,
      141,  143,  146,  145,  129,  142,  142,  127,    0,   71,
      136,  135,    0,    0,    0,  122,  123,    0,  133,  119,
      134,    0,  133,  123,  131,    0,   58,  116,  147,  117,
        0,  115,    0,    0,  126,  125,  109,  123,  117,  121,
      108,    0,    0,  102,  104,   41,  117,  112,   84,  112,
        0,   99,   99,  108,    0,   45,    0,    0,  101,    0,
      103,  102,   92,   92,  106,   93,   97,    0,    0,   99,
       98,  100,   82,   80,   83,    0,  110,    0,   81,   81,
       80,    0,   90,   89,    0,   90,   77,   67,   66,  253,

        0,   92,   82,   77,   79,   78,   66,   61,   60,   58,
       54,  253,  253,    0,   39,  253,  253,   48
    } ;

static yyconst short int yy_def[219] =
    {   0,
      217,    1,  217,  217,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  217,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  217,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  217,  218,
      218,  217,  218,  218,  218,  218,  218,  218,  218,  218,
      217,  218,  218,  218,  217,  218,  217,  218,  218,  217,
      218,  218,  217,  218,  218,  218,  217,  218,  217,  217,
      218,  218,  217,  218,  218,  217,  217,  217,  218,  217,

      218,  217,  217,  217,  217,  218,  217,  217,  217,  218,
      217,  217,  217,  218,  217,  217,    0,  217
    } ;

static yyconst short int yy_nxt[298] =
    {   0,
        4,    4,    5,    4,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,    6,
        7,    8,    9,   10,   12,    9,    9,   13,   14,   15,
        9,   16,   17,    9,   18,   19,    9,   20,    9,    9,
        9,    9,    4,    9,   23,   26,   28,   66,   24,   21,
       51,   27,   34,   39,   29,   68,   35,   52,   60,   36,
       40,   25,  216,   61,   37,   41,   69,   42,   76,   72,
       76,   53,  120,  102,   53,   87,  104,   67,   73,  104,
       88,  103,  156,  171,  172,  159,  145,  180,  181,  215,
      157,  202,  214,  202,  213,  212,  211,  210,  209,  175,

      208,  207,  203,  145,  203,  206,  205,  204,  201,  200,
      199,  198,  197,  196,  195,  194,  175,  193,  203,  192,
      203,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  179,  178,  177,  176,  174,  173,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,

      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   86,   85,   84,   83,   82,   81,   80,
       79,   78,   77,   75,   74,   71,   70,   65,   64,   63,
       62,   59,   58,   57,   56,   55,   54,   50,   49,   48,
       47,   46,   45,   44,   43,   38,   33,   32,   31,   30,
       22,  217,    3,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217

    } ;

static yyconst short int yy_chk[298] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,   10,   39,    7,  218,
       27,    8,   15,   17,   10,   40,   15,   27,   34,   15,
       17,    7,  215,   34,   15,   17,   40,   17,   46,   43,
       46,   27,  120,   74,   27,   57,   75,   39,   43,   75,
       57,   74,  137,  156,  156,  159,  120,  166,  166,  211,
      137,  196,  210,  202,  209,  208,  207,  206,  205,  159,

      204,  203,  196,  120,  202,  199,  198,  197,  194,  193,
      191,  190,  189,  187,  185,  184,  159,  183,  196,  182,
      202,  181,  180,  177,  176,  175,  174,  173,  172,  171,
      169,  164,  163,  162,  160,  158,  157,  155,  154,  151,
      150,  149,  148,  147,  146,  145,  142,  140,  139,  138,
      135,  134,  133,  131,  130,  129,  127,  126,  122,  121,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  103,  102,  101,  100,   99,   98,
       97,   96,   95,   93,   92,   91,   90,   89,   88,   87,
       85,   84,   83,   82,   81,   80,   79,   78,   77,   76,

       73,   72,   71,   70,   69,   68,   67,   63,   62,   61,
       60,   59,   58,   56,   55,   54,   53,   52,   51,   50,
       49,   48,   47,   45,   44,   42,   41,   38,   37,   36,
       35,   33,   32,   31,   30,   29,   28,   26,   25,   24,
       23,   22,   20,   19,   18,   16,   14,   13,   12,   11,
        6,    3,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "palabrasColombianas.l"
#define INITIAL 0
#line 3 "palabrasColombianas.l"
#include <stdio.h>

int lineas = 1;
int palabras = 0;
int caracteres = 0;


int mija = 0;
int pa = 0;
int charra = 0;
int filo = 0;
int camellar = 0;
int mecatear = 0;
int manes = 0;
int vole = 0;
int porra = 0;
int buchipluma = 0;
int berraca = 0;
int pispo = 0;
int tragada = 0;
int mata_pasiones = 0;
int loliar = 0;
int chichiguita = 0;
int checheres = 0;
int pieza = 0;
int trapito = 0;
int guaros = 0;
int ome = 0;
int chichipato = 0;
int parchese = 0;
int primita = 0;
int mor = 0;
int sizas = 0;
int jetota = 0;
int bacano = 0;
int sinverguenzas = 0;
int guayabo = 0;
int empinando = 0;
int amanada = 0;
int echada_palante = 0;

void imprimirResultado();
#line 546 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "palabrasColombianas.l"


#line 700 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 218 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 253 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "palabrasColombianas.l"
{ mija++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "palabrasColombianas.l"
{ pa++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "palabrasColombianas.l"
{ charra++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "palabrasColombianas.l"
{ filo++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "palabrasColombianas.l"
{ camellar++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "palabrasColombianas.l"
{ mecatear++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "palabrasColombianas.l"
{ manes++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "palabrasColombianas.l"
{ vole++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "palabrasColombianas.l"
{ porra++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "palabrasColombianas.l"
{ buchipluma++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "palabrasColombianas.l"
{ berraca++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "palabrasColombianas.l"
{ pispo++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "palabrasColombianas.l"
{ tragada++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "palabrasColombianas.l"
{ mata_pasiones++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "palabrasColombianas.l"
{ loliar++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "palabrasColombianas.l"
{ chichiguita++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "palabrasColombianas.l"
{ checheres++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "palabrasColombianas.l"
{ pieza++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "palabrasColombianas.l"
{ trapito++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "palabrasColombianas.l"
{ guaros++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "palabrasColombianas.l"
{ ome++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "palabrasColombianas.l"
{ chichipato++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "palabrasColombianas.l"
{ parchese++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "palabrasColombianas.l"
{ primita++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "palabrasColombianas.l"
{ mor++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "palabrasColombianas.l"
{ sizas++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "palabrasColombianas.l"
{ jetota++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "palabrasColombianas.l"
{ bacano++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "palabrasColombianas.l"
{ sinverguenzas++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "palabrasColombianas.l"
{ guayabo++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "palabrasColombianas.l"
{ empinando++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "palabrasColombianas.l"
{ amanada++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "palabrasColombianas.l"
{ echada_palante++; palabras++; caracteres += yyleng; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "palabrasColombianas.l"
{ palabras++; caracteres += yyleng; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "palabrasColombianas.l"
{ lineas++; caracteres++; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "palabrasColombianas.l"
{ caracteres++; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "palabrasColombianas.l"
ECHO;
	YY_BREAK
#line 968 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 218 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 218 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 217);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 90 "palabrasColombianas.l"


void imprimirResultado() {
    printf("\n=== PALABRAS DEL LEXICO COLOMBIANO ENCONTRADAS ===\n\n");
    
    printf("Expresiones comunes:\n");
    printf("Mija/Mijita: %d\n", mija);
    printf("Pa': %d\n", pa);
    printf("Charra: %d\n", charra);
    printf("Aguantar filo: %d\n", filo);
    printf("Camellar: %d\n", camellar);
    printf("Mecatear: %d\n", mecatear);
    printf("Manes: %d\n", manes);
    printf("Vole (faltar el respeto): %d\n", vole);
    printf("Largar pa' la porra: %d\n", porra);
    printf("Buchipluma: %d\n", buchipluma);
    printf("Berraca: %d\n", berraca);
    
    printf("\nTerminos de relaciones y apariencia:\n");
    printf("Pispo: %d\n", pispo);
    printf("Tragada (enamorada): %d\n", tragada);
    printf("Mata pasiones: %d\n", mata_pasiones);
    printf("Primita: %d\n", primita);
    printf("Mor (amor): %d\n", mor);
    
    printf("\nActividades y objetos:\n");
    printf("Loliar: %d\n", loliar);
    printf("Chichiguita: %d\n", chichiguita);
    printf("Checheres: %d\n", checheres);
    printf("Pieza: %d\n", pieza);
    printf("Trapito: %d\n", trapito);
    printf("Guaros: %d\n", guaros);
    printf("Empinando el codo: %d\n", empinando);
    
    printf("\nExpresiones varias:\n");
    printf("Ome: %d\n", ome);
    printf("Chichipato: %d\n", chichipato);
    printf("Parchese: %d\n", parchese);
    printf("Sizas: %d\n", sizas);
    printf("Jetota: %d\n", jetota);
    printf("Bacano: %d\n", bacano);
    printf("Sinverguenzas: %d\n", sinverguenzas);
    printf("Guayabo: %d\n", guayabo);
    printf("Amanada: %d\n", amanada);
    printf("Echada pa'lante: %d\n", echada_palante);
    
    printf("\n=== ESTADISTICAS GENERALES ===\n");
    printf("Total de lineas: %d\n", lineas);
    printf("Total de palabras: %d\n", palabras);
    printf("Total de caracteres: %d\n", caracteres);
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        printf("Uso: %s <archivo.txt>\n", argv[0]);
        return 1;
    }

    FILE *archivo = fopen(argv[1], "r");
    if (!archivo) {
        printf("Error: No se pudo abrir el archivo '%s'\n", argv[1]);
        return 1;
    }

    yyin = archivo;
    yylex();
    fclose(archivo);

    imprimirResultado();

    return 0;
}Echadas pa’ delante
Paula Andrea Gallego Henao.
Hace algunos años, en un pueblito antioqueño, dos amigas, Cecilia y Fernanda estaban sentadas en una banca del parque, conversando y reflexionando sobre la vida.
—Ay, mija, yo sí quisiera irme pa’ Medellín… a vivir el sueño —decía Cecilia con ojos ensoñadores.
—¡Oigan a esta tan charra! ¿Cuál sueño? Irse pa’ por allá a aguantar filo, camellar en cualquier parte pa’ recoger unos pesos que no le van a alcanzar ni pa’ mecatear. No, mija, acá estamos muy tranquilas —le respondió Fernanda mientras chupaba una paleta de coco.
—¿Le parece tranquilidad madrugar a las cuatro a trabajar la tierra, y que no lo dejen a uno ni tomarse un tinto porque después hay que despacharle el almuerzo a esos manes que trabajan allá? Hoy porque me le volé a mi amá, si no, allá estaba.
—Ay no, yo sé. Si usted se quiere largar pa’ la porra, váyase, mijita. Pero deje de ser buchipluma: habla y habla y no hace nada —le dijo Fernanda, hastiada de tener la misma conversación con Cecilia cada domingo. Luego se paró de la banca y se fue.
Cecilia pensó que lo que le había dicho Fernanda era cierto. Siempre amenazaba con irse a la ciudad, pero al final del día seguía en el pueblo, haciendo lo mismo de lo que tanto se quejaba.
Pero ese día se decidió, ya no la llamarían buchipluma. Sería berraca y se iría para Medellín, a trabajar y a cumplir esos sueños que le rondaban la cabeza todos los días.
A la mañana siguiente, Cecilia y Fernanda se bajaron del bus en la Terminal del Norte, en Medellín. Ambas habían sacado sus ahorros, comprado los pasajes y empacado sus pertenencias más importantes.
Juntas, andando y preguntando, encontraron ese mismo día una casita pequeña donde vivir, y en esa misma semana consiguieron trabajo para sostenerse.
Después de un mes, Cecilia estaba feliz con su logro, aunque Fernanda no tanto. En su trabajo la explotaban y el dinero apenas le alcanzaba para el arriendo y algo de comida. La situación de Cecilia no era muy diferente, pero había algo que la mantenía ilusionada, se había enamorado.
—Ay, mija, yo estoy pero tragada de ese pelado, ¿oyó? ¡Es tan pispo! —le decía Cecilia un sábado en la tarde.
—¿Cuál pispo? Si es más feo que un carro por debajo. Lo que pasa es que usted está más tragada que calzón de loca, entonces lo ve con esos ojos de ternero a medio morir, y no oye, no ve ni entiende nada de la realidad —le respondió Fernanda riéndose.
—Usted tan mata pasiones, de verdad. Venga, más bien vayamos al centro a loliar un ratico. Vea que con las horas extras que hice me dieron una chichigüita de más y podemos comprarnos unas chécheres pa’ adornar la pieza. Y de pronto se nos atraviesa un trapito pa’ nosotras de una vez —le propuso Cecilia, tomándola de las manos y revoloteando las pestañas.
—Hágale, pues. Pero con la condición de que después me invite a unos guaros —aceptó Fernanda, dejándose convencer.
Ambas recorrieron el centro de Medellín de arriba para abajo, viendo y comprando algunas cosillas que podían costear con el dinero de Cecilia.
—Amiga, Javier me acaba de mandar un mensajito: que nos encontremos con él en la 45 pa’ irnos a bailar —le dijo Cecilia emocionada.
—Ujum… pero ese como es de chichipato, ¿nos va a invitar?
—De más que sí. Eso dijo.
Cuando llegaron al bar, se encontraron con una escena desagradable, Javier estaba con otra mujer en brazos, dándose unos besos que hasta da pena describirlos.
A Cecilia se le vino el mundo encima, pero Fernanda, al ver el descaro del tipo, lo agarró de los pelos.
—Oíste, vos sí querías que te cascaran, ¿no? Pero hoy, mijo, me la pusiste a boquita que querés —le gritó Fernanda, echando espuma por la boca.
—¡Uy, nea! ¿Qué le pasa? —dijo Javier, sorprendido y nervioso—. Parchese, que eso no es nada. Ella es solo una primita, ¿sí o qué, mor?
—Sizas, sizas, él es mi primo hermano —respondió la mujer, viéndolos con cara de susto.
—¿Ah, sí? Pues ahora resulta que los primos se besan en la jetota. Vea qué tan bacano —y sin más, Fernanda alzó el puño y se lo estampó en la cara—. Este es el saludo que yo le doy a los sinvergüenzas como usted.
Agarró a Cecilia de la mano y se fueron del lugar.
—¡Ah, pero el guaro me lo debe, no, Cecilia! —dijo Fernanda, y Cecilia soltó la risa.
Al día siguiente amanecieron con una fuerte resaca, preparando caldo de pollo con arepa.
—Ay no, qué es este guayabo tan horrible. No vuelvo a tomar —decía Cecilia mientras se hacía una soda con limón.
—Sí, ome, y en quince días está empinando el codo otra vez —contestó Fernanda.
Ambas rieron, pero luego cayó un silencio que solo interrumpía el pitido de la olla cocinando el caldo.
—Fernandita, yo creo que mejor nos devolvemos pa’l pueblo. Esto acá está muy jodido. Éramos más felices y estábamos más tranquilas allá en nuestra tierrita.
—Yo estoy muy amañada —dijo Fernanda, mirando por la ventana las casas de ladrillo anaranjado—. Nosotras somos berracas y podemos con esto. Que un man que no valía la pena te la haya jugado no es razón de peso pa’ apagar todos esos sueños de los que usted me hablaba, Cecilia.
Cecilia la miró y se le humedecieron los ojos.
—Acá las cosas son duras, hermana, ¿pero a nosotras cuándo nos ha quedado grande un desafío? —continuó Fernanda.
Cecilia rompió en llanto y se abrazó a su amiga.
—Yo no sé usted, pero yo me vine pa’ Medellín a vivir bien bueno, a lograr mis sueños, a que crezcamos juntas cada día y a pasar cada experiencia, por dura que sea, pero juntas —le dijo entre lágrimas.
Y así fue. Juntas se esforzaron durante años, estudiaron, avanzaron, y todo el sacrificio valió la pena. Más aún porque su amistad siguió intacta, sin importar las circunstancias.
Porque lo más bello de Medellín no es solo la ciudad, sino su gente echada pa’lante.
